apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: prometheus-gateway-params
  namespace: monitoring
spec:
  kube:
    podTemplate:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: ["amd64"]
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: ["arm64"]
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "jenkins"
        effect: "NoSchedule"
      - key: "instance"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"
      - key: "dedicated"
        operator: "Equal"
        value: "addons"
        effect: "NoSchedule"
    envoyContainer:
      image:
        registry: cr.kgateway.dev/kgateway-dev
        repository: envoy-wrapper
        tag: v2.0.2
        pullPolicy: Always 